name: Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
    - name: Installing packages
      run: npm ci
    - name: Running tests
      run: npm t      
    - name: Deploying to restlr.io
      run: npm run deploy
