name: Node CI

on: [push]

env:
  DEPLOY_SERVER: cronos.illunis.net
  DEPLOY_SERVER_PORT: 36077

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test:all
      env:
        CI: true
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
    - name: Adding deploy server to known_hosts
      run: |
        ssh-keyscan -t ecdsa -p ${{ env.DEPLOY_SERVER_PORT }} ${{ env.DEPLOY_SERVER }} >> ~/.ssh/known_hosts
        ssh-keyscan -t ecdsa -p ${{ env.DEPLOY_SERVER_PORT }} 45.10.26.70 >> ~/.ssh/known_hosts
    - name: Installing pm2
      run: npm i -g pm2
    - name: Deploying restlr.io
      run: pm2 deploy ecosystem.config.js production
